### PR TITLE
Add uptime information for HA and update unit tests

### PR DESCRIPTION
**Pull request by freeDom-**
Add uptime information for HA
Add a unit test for the case that some of the container information is not exposed.

### CODE REVIEW

**Comment by freeDom-** [comment]
@fabaff Can this PR get merged?

**Comment by oneseventhree** [comment]
please merge this :) uptimee would be great!

**Review by fabaff — APPROVED** [review]
Looks good to me.

**Comment by oneseventhree** [comment]
> Looks good to me.

Thanks! Will this be in the 2023.6.4 release or 
2023.7.x?

**Comment by fabaff** [comment]
2023.6.x will only contain bugfixes.

**Comment by freeDom-** [comment]
This is only the API changes. We need to build a new API version, change the used version in HA core and finally add the sensors to HA core as well.

You see there is still some work left to do. I hope that it finds it way into 2023.7 or 2023.8

**Pull request merged**
